server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # 注意这里的GMT+8，用于解决数据库时差8问题
    url: jdbc:mysql://localhost:3306/newxiaokui?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: 199710
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=10,maximumSize=200,expireAfterWrite=3600s
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理(面向接口),true为cglib动态代理(面向继承)

beetl-beetlsql.dev: true
beetlsql:
  dev: true # 是否是开发环境，默认为true
  basePackage: site.xiaokui
  daoSuffix: Dao
