beetl-beetlsql.dev: false
beetlsql:
  dev: false #是否是开发环境，默认为true
  basePackage: site.xiaokui
  daoSuffix: Dao

jasypt:
  encryptor:
    password: '@kpwd@'

spring:
  resources:
    static-locations: classpath:/static/
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://120.79.20.49:3306/newxiaokui?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: ENC(MdrHx2+xFQGOmHhMINpEH/Is2n2crwgOT5t3TmVmZIlIsbjdQKcZqn+g4M+ZbZPS)
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 120.79.20.49
    port: 6379
    password: ENC(yO1ze7HVhFu0y90o6ZJDVxiBEAaxlGs5DGWxpCmSVILsouH2XE1TlKWg+K8Bw00w)

xiaokui:
  basePath: /xiaokui/
  # 静态资源路径
  staticLibPath: ${xiaokui.basePath}/lib/
  # 博客上传路径
  blogUploadPath: ${xiaokui.basePath}/upload/
  # 音乐保存目录
  blogMusicPath: ${xiaokui.basePath}/music/
  # 头像上传目录
  avatarUploadPath: ${xiaokui.basePath}/avatar/
  # 系统日志目的地
  logsPath: ${xiaokui.basePath}/logs/
  # 日志文件名
  logName: remote.log

logging:
  level:
    root: info
    site.xiaokui: info