server:
  port: 9090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

spring:
  profiles:
    #需要激活的profile local或remote
    active: local
  mvc:
    view:
      prefix: /
    pathmatch:
      use-suffix-pattern: true #忽略小数点后缀，如/test.tss仍然是匹配/test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理(面向接口),true为cglib动态代理(面向继承)

xiaokui:
  # 最多访问数量
  most-view: 8
  # 最近上传数量
  recent-upload: 0
  # 最近上传数量
  recent-update: 8
  # 推荐数量
  recommend-count: 16
  # 单个IP单日对单篇博客最大贡献访问量
  single-ip-contribute-blog: 5
  # 单个IP单日对所有博客最大贡献访问量
  single-ip-contribute--all-blog: 20
  # 单个用户单日对单篇博客最大贡献访问量
  single-user-contribute-blog: 20
  # 单个用户单日对所有博客最大贡献访问量，两个限制条件不冲突
  single-user-contribute--all-blog: 40
  # 是否启用shiro，关闭后系统所有权限控制将会失效
  enable-shiro: true
  session-alive: 60 * 60 * 24
  session-check: 60 * 60 * 6

oauth2:
  loginUrl: https://www.xiaokui.site/aabb