server:
  port: 8971

spring:
  application:
    name: order-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # 注意这里的GMT+8，用于解决数据库时差8问题
    url: jdbc:mysql://localhost:3306/k-mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: 199710
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
      instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}

snowflake:
  workerId: 10
  dataCenterId: 11






