server:
  port: 9090

spring:
  profiles:
    active: dev
  freemarker:
    check-template-location: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  data:
    redis:
      repositories:
        enabled: false

  #配置 Jpa
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

xiaokui:
  # 最多访问数量
  most-view: 8
  # 最近上传数量
  recent-upload: 0
  # 最近上传数量
  recent-update: 8
  # 推荐数量
  recommend-count: 16
  # 单个IP单日对单篇博客最大贡献访问量
  single-ip-contribute-blog: 5
  # 单个IP单日对所有博客最大贡献访问量
  single-ip-contribute--all-blog: 20
  # 单个用户单日对单篇博客最大贡献访问量
  single-user-contribute-blog: 20
  # 单个用户单日对所有博客最大贡献访问量，两个限制条件不冲突
  single-user-contribute--all-blog: 40

  basePath: /xiaokui/product
  # 文件资源路径
  file-path: ${xiaokui.basePath}/file/
  # 静态资源路径
  staticLibPath: ${xiaokui.basePath}/lib/
  # 博客上传路径
  blogUploadPath: ${xiaokui.basePath}/upload/
  # 音乐保存目录
  blogMusicPath: ${xiaokui.basePath}/music/
  # 头像上传目录
  avatarUploadPath: ${xiaokui.basePath}/avatar/

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50

#七牛云
qiniu:
  # 文件大小 /M
  max-size: 15

#邮箱验证码有效时间/秒
code:
  expiration: 300

#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEA0vfvyTdGJkdbHkB8mp0f3FE0GYP3AYPaJF7jUd1M0XxFSE2ceK3k2kw20YvQ09NJKk+OMjWQl9WitG9pB6tSCQIDAQABAkA2SimBrWC2/wvauBuYqjCFwLvYiRYqZKThUS3MZlebXJiLB+Ue/gUifAAKIg1avttUZsHBHrop4qfJCwAI0+YRAiEA+W3NK/RaXtnRqmoUUkb59zsZUBLpvZgQPfj1MhyHDz0CIQDYhsAhPJ3mgS64NbUZmGWuuNKp5coY2GIj/zYDMJp6vQIgUueLFXv/eZ1ekgz2Oi67MNCk5jeTF2BurZqNLR3MSmUCIFT3Q6uHMtsB9Eha4u7hS31tj1UWE+D+ADzp59MGnoftAiBeHT7gDMuqeJHPL4b+kC+gzV4FGTfhR9q3tTbklZkD2A==
