server:
  port: 9001

spring:
  application:
    name: eureka-server-9002

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/, http://localhost:9001/eureka/
  server:
    enableSelfPreservation: false
