server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    #需要激活的profile local或remote
    active: remote
  mvc:
    view:
      prefix: /
    pathmatch:
      use-suffix-pattern: true #忽略小数点后缀，如/test.tss仍然是匹配/test
  http:
    encoding:
      charset: UTF-8
      force: true
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理(面向接口),true为cglib动态代理(面向继承)

#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

xiaokui:
  # 最对访问数量
  most-view: 8
  # 最近上传数量
  recent-upload: 8
  # 推荐数量
  recommend-count: 16
  # 单个IP单日对单篇博客最大贡献访问量
  single-ip-contribute-blog: 10
  # 单个IP单日对所有博客最大贡献访问量
  single-ip-contribute--all-blog: 40
  # 单个用户单日对单篇博客最大贡献访问量
  single-user-contribute-blog: 20
  # 单个用户单日对所有博客最大贡献访问量，两个限制条件不冲突
  single-user-contribute--all-blog: 80
  session-alive: 60 * 60 * 24
  session-check: 60 * 60 * 6
