# 该属性置为true的时候，核心Logger（包含嵌入式容器、hibernate、spring）会输出更多内容，但是你自己应用的日志并不会输出为DEBUG级别
debug: false

server:
  port: 8080
  servlet:
    context-path: /

base-path: /xiaokui
static-adminlte-path: ${base-path}/libs
# 如果修改了这个目录，请务必修改FileUtil下的 UPLOAD_PATH 值
blog-upload-path: ${base-path}/upload

spring:
#  redis:
#    host: localhost
#    port: 6379
#    password:
  profiles:
    active: local
#    spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
#    spring.jackson.time-zone=GMT+8
  mvc:
#    static-path-pattern: /static/**
    view:
#      prefix: /WEB-INF/view
       prefix: /
    pathmatch:
      use-suffix-pattern: true #忽略小数点
  resources:
    static-locations: classpath:/static/,file:${static-adminlte-path}
  http:
    converters:
      preferred-json-mapper: fastjson
#    multipart:
#      max-request-size: 100MB #最大请求大小
#      max-file-size: 100MB #最大文件大小
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: static/**,/**
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理

beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: beetl/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false

beetlsql:
  basePackage: site.xiaokui.module.sys

---
spring:
  profiles: local
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/newxiaokui?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: 199710
    driver-class-name: com.mysql.jdbc.Driver

#配置文件里面的设置，会覆盖logback里面的
logging:
  level:
    root: info
    site.xiaokui: debug
  file: local.log
---
spring:
  profiles: online
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/newxiaokui?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: 199710
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    root: info
    site.xiaokui: info
  file: logs/online.log #使用默认配置时，path和file只能选一个（如果同时有，那么只有file生效）
  file.max-size: 6MB
  file.max-history: 30
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{32}- %msg%n"
    level: "%5p"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{32}- %msg%n"
