server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    #需要激活的profile local或remote
    active: remote
  mvc:
    view:
      prefix: /
    pathmatch:
      use-suffix-pattern: true #忽略小数点后缀，如/test.tss仍然是匹配/test
  http:
    encoding:
      charset: UTF-8
      force: true
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理(面向接口),true为cglib动态代理(面向继承)

#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

xiaokui:
  session-alive: 60 * 60 * 24
  session-check: 60 * 60 * 6
  most-view: 8
  recent-upload: 8
  recommend-count: 16
