server:
  port: 7070
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

spring:
  profiles:
#    active: 0-base
    active: 1-read-write
#    active: 0-base
#    active: 0-base
#    active: 0-base

  mvc:
    view:
      prefix: /
    pathmatch:
      use-suffix-pattern: true #忽略小数点后缀，如/test.tss仍然是匹配/test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  aop:
    proxy-target-class: true #false为启用jdk默认动态代理(面向接口),true为cglib动态代理(面向继承)

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: db.entity

logging:
  level.root: info
  level.db: debug
  level.org.springframework.web: debug
  level.redis: debug
  level.jdbc: debug
  level.org.apache.ibatis: debug
  level.org.springframework.transaction: debug
  level.org.springframework.jdbc: debug

