server:
  port: 8000

spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      default-filters:
        - name: Hystrix
          args:
            name: default
            fallbackUri: 'forward:/defaultfallback'
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 2  # 流速每秒
            redis-rate-limiter.burstCapacity: 4  # 令牌桶的容积
            key-resolver: "#{@ipAddressKeyResolver}" #SPEL表达式去的对应的bean
  redis:
    # redis机器最好与网关在同一台机器上，便于最大化限流效果
    host: localhost
    port: 6379
    timeout: 6000
    database: 1
    lettuce:
      pool:
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）,如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-idle: 8   # 连接池中的最大空闲连接 ，默认值也是8
        max-wait: 100 # # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        min-idle: 2    # 连接池中的最小空闲连接 ，默认值也是0
      shutdown-timeout: 100ms

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
      instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000






