server:
  port: 8981

spring:
  application:
    name: product-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # 注意这里的GMT+8，用于解决数据库时差8问题
    url: jdbc:mysql://localhost:3306/k-mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: 199710
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
      instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}

# 雪花算法留个workId、dataCenterId的bit位数分别为5位、5位，即取值范围为0 ～ 2^6-1=31，总大小为32 * 32 = 1024
snowflake:
  workerId: 10
  dataCenterId: 2






