### 第一个测试，分页查询数据
POST http://127.0.0.1:7070/page?offset=2&size=5
Content-Type: application/json

{
  "head": {
    "sign_type": "MD5",
    "version": "1.0",
    "serial_no": "",
    "sign": ""
  },
  "data": {
  }
}

### 第二个测试，查询全部数据
POST http://127.0.0.1:7070/query
Content-Type: application/json

{
  "head": {
    "sign_type": "MD5",
    "version": "1.0",
    "serial_no": "",
    "sign": ""
  },
  "data": {
  }
}

### 第三个测试，查询单个数据
POST http://127.0.0.1:7070/query?id=14
Content-Type: application/json

{
  "head": {
    "sign_type": "MD5",
    "version": "1.0",
    "serial_no": "",
    "sign": ""
  },
  "data": {
  }
}

### 第四个测试，数据汇总 sum + group by
POST http://127.0.0.1:7070/groupByAndSum?sum=age&groupBy=sex
Content-Type: application/json

{
  "head": {
    "sign_type": "MD5",
    "version": "1.0",
    "serial_no": "",
    "sign": ""
  },
  "data": {
  }
}