server:
  port: 7001

spring:
  application:
    name: eureka-server

eureka:
  dashboard:
    path: /
  server:
    renewal-percent-threshold: 0.49  # 指定每分钟需要收到的续约次数的阈值，默认值就是：0.85
    enable-self-preservation: false  # 关闭服务器自我保护，客户端心跳检测15分钟内错误达到80%服务会保护，导致别人还认为是好用的服务
    eviction-interval-timer-in-ms: 20000  # 清理间隔（单位毫秒，默认是60*1000）将客户端剔除的服务在服务注册列表中剔除
  client:
    register-with-eureka: true  # 是否将自身的实例信息注册到eureka服务器
    registry-fetch-interval-seconds: 10  #从eureka服务端获取注册信息的间隔时间
    fetch-registry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server ，是否从eureka服务端获取注册信息，消费者需要配置true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-expiration-duration-in-seconds: 30 # 服务失效时间，默认值90秒，开发时可以调小一点
    lease-renewal-interval-in-seconds: 10 # 服务续约(renew)的间隔，默认为30秒