server:
  port: 9000
  servlet:
    context-path: /

spring:
  profiles:
    #需要激活的profile local或remote
    active: local
  application:
    name: main-cosumer
  dubbo:
    server: true
    registry:
      address: zookeeper://localhost:2181
  mvc:
    view:
      prefix: /
    pathmatch:
      use-suffix-pattern: true #忽略小数点后缀，如/test.tss仍然是匹配/test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  http:
    encoding:
      charset: UTF-8
      force: true
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理(面向接口),true为cglib动态代理(面向继承)

#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

oauth2:
  loginUrl: https://www.xiaokui.site/aabb